# Goblin Camp cargo-deny configuration

[licenses]
# Allow common open source licenses used in our dependencies
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "Zlib",
    "Unicode-3.0",
]

[bans]
# Warn about multiple versions but don't fail
multiple-versions = "warn"
# Allow wildcard dependencies
wildcards = "allow"

[sources]
# Only allow crates.io
unknown-registry = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]